sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t reactapp .

script:
  - docker run -e CI=true reactapp npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-608531295111"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
